// Code generated by abstraction-idl from abstraction-facade/facade.thrift. DO NOT EDIT.

package facade

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

var ScopeNames = []string{"any", "local", "remote"}

const ScopeAny = "any"

const ScopeLocal = "local"

const ScopeRemote = "remote"

const ScopeUnknown = "refuse"

var ResolutionStatusNames = []string{"resolved", "unavailable", "forbidden", "incompatible", "unmet_requirements", "not_ready", "invalid_request"}

const ResolutionStatusResolved = "resolved"

const ResolutionStatusUnavailable = "unavailable"

const ResolutionStatusForbidden = "forbidden"

const ResolutionStatusIncompatible = "incompatible"

const ResolutionStatusUnmetRequirements = "unmet_requirements"

const ResolutionStatusNotReady = "not_ready"

const ResolutionStatusInvalidRequest = "invalid_request"

const ResolutionStatusUnknown = "refuse"

type ResolveRequest struct {
	Capability string
	Contracts  []string
	Guarantees []string
	Scope      string
}

type ServiceReference struct {
	Provider   string
	Capability string
	Contract   string
	Guarantees []string
	Scope      string
	Transport  string
	Endpoint   string
}

type ResolveResult struct {
	Status    string
	Reference *ServiceReference
}

type OAResolverResolveArguments struct {
	Request ResolveRequest
}

type OAServiceFrame struct {
	Version   int32
	Service   string
	Method    string
	Arguments Raw
}

type OAServiceReply struct {
	Version int32
	Service string
	Method  string
	Ok      bool
	Payload Raw
}

type OAServiceError struct {
	Code    string
	Message string
}

type OAResolverResolveResult struct {
	Value ResolveResult
}

func encResolveRequest(out []byte, v *ResolveRequest, depth int) []byte {
	if v.Scope != "any" && v.Scope != "local" && v.Scope != "remote" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "capability")
	out = append(out, ':', ' ')
	out = esc(out, v.Capability)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "contracts")
	out = append(out, ':', ' ')
	out = strs(out, v.Contracts, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "guarantees")
	out = append(out, ':', ' ')
	out = strs(out, v.Guarantees, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "scope")
	out = append(out, ':', ' ')
	out = esc(out, v.Scope)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encServiceReference(out []byte, v *ServiceReference, depth int) []byte {
	if v.Scope != "any" && v.Scope != "local" && v.Scope != "remote" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "provider")
	out = append(out, ':', ' ')
	out = esc(out, v.Provider)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "capability")
	out = append(out, ':', ' ')
	out = esc(out, v.Capability)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "contract")
	out = append(out, ':', ' ')
	out = esc(out, v.Contract)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "guarantees")
	out = append(out, ':', ' ')
	out = strs(out, v.Guarantees, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "scope")
	out = append(out, ':', ' ')
	out = esc(out, v.Scope)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "transport")
	out = append(out, ':', ' ')
	out = esc(out, v.Transport)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "endpoint")
	out = append(out, ':', ' ')
	out = esc(out, v.Endpoint)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encResolveResult(out []byte, v *ResolveResult, depth int) []byte {
	if v.Status != "resolved" && v.Status != "unavailable" && v.Status != "forbidden" && v.Status != "incompatible" && v.Status != "unmet_requirements" && v.Status != "not_ready" && v.Status != "invalid_request" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "status")
	out = append(out, ':', ' ')
	out = esc(out, v.Status)
	if v.Reference != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "reference")
		out = append(out, ':', ' ')
		out = encServiceReference(out, v.Reference, depth+1)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAResolverResolveArguments(out []byte, v *OAResolverResolveArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "request")
	out = append(out, ':', ' ')
	out = encResolveRequest(out, &v.Request, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceFrame(out []byte, v *OAServiceFrame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "arguments")
	out = append(out, ':', ' ')
	out = append(out, v.Arguments...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceReply(out []byte, v *OAServiceReply, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "ok")
	out = append(out, ':', ' ')
	if v.Ok {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "payload")
	out = append(out, ':', ' ')
	out = append(out, v.Payload...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceError(out []byte, v *OAServiceError, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "message")
	out = append(out, ':', ' ')
	out = esc(out, v.Message)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAResolverResolveResult(out []byte, v *OAResolverResolveResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encResolveResult(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *ResolveResult) []byte {
	return append(encResolveResult(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) decodeResolveRequest() (*ResolveRequest, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ResolveRequest{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "capability":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Capability = x
			case "contracts":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.Contracts = x
			case "guarantees":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.Guarantees = x
			case "scope":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Scope = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	if v.Scope != "any" && v.Scope != "local" && v.Scope != "remote" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeServiceReference() (*ServiceReference, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ServiceReference{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "provider":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Provider = x
			case "capability":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Capability = x
			case "contract":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Contract = x
			case "guarantees":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.Guarantees = x
			case "scope":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Scope = x
			case "transport":
				if seen&32 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 32
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Transport = x
			case "endpoint":
				if seen&64 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 64
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Endpoint = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&127 != 127 {
		return nil, r.refuse("missing_field")
	}
	if v.Scope != "any" && v.Scope != "local" && v.Scope != "remote" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeResolveResult() (*ResolveResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ResolveResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "status":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Status = x
			case "reference":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeServiceReference()
				if err != nil {
					return nil, err
				}
				v.Reference = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	if v.Status != "resolved" && v.Status != "unavailable" && v.Status != "forbidden" && v.Status != "incompatible" && v.Status != "unmet_requirements" && v.Status != "not_ready" && v.Status != "invalid_request" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOAResolverResolveArguments() (*OAResolverResolveArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAResolverResolveArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "request":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeResolveRequest()
				if err != nil {
					return nil, err
				}
				v.Request = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceFrame() (*OAServiceFrame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceFrame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "arguments":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Arguments = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceReply() (*OAServiceReply, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceReply{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "ok":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Ok = x
			case "payload":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Payload = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceError() (*OAServiceError, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceError{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "message":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Message = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAResolverResolveResult() (*OAResolverResolveResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAResolverResolveResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeResolveResult()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func Decode(in []byte) (*ResolveResult, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeResolveResult()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// Refusals is in the order two of them are chosen between.

var Refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"}

func RefusalRank(word string) int {
	for i, w := range Refusals {
		if w == word {
			return i
		}
	}
	return -1
}

// A transport consumes or copies frames before returning. WriteFrame is one-way.
type FrameWriter interface{ WriteFrame([]byte) error }
type DispatchError string

func (e DispatchError) Error() string { return string(e) }
func servicePayload(frame []byte) (*OAServiceFrame, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return nil, DispatchError("unknown_version")
	}
	return v, nil
}

// ExchangeFrame returns the response associated with this call. Correlation,
// serialization and deadlines belong to the transport, not this codec.
type FrameExchanger interface{ ExchangeFrame([]byte) ([]byte, error) }
type ServiceError struct {
	Code    string
	Message string
}

func (e *ServiceError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return e.Code
}
func serviceResponse(frame []byte, service, method string) (Raw, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceReply()
	if err != nil {
		return "", err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return "", r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return "", DispatchError("unknown_version")
	}
	if v.Service != service || v.Method != method {
		return "", DispatchError("mismatched_response")
	}
	if !v.Ok {
		r = &reader{buf: []byte(v.Payload), depth: 1}
		r.ws()
		e, err := r.decodeOAServiceError()
		if err != nil {
			return "", err
		}
		r.ws()
		if r.pos != len(r.buf) {
			return "", r.refuse("trailing_bytes")
		}
		if e.Code == "" {
			return "", DispatchError("invalid_error")
		}
		return "", &ServiceError{Code: e.Code, Message: e.Message}
	}
	return v.Payload, nil
}
func serviceReply(v *OAServiceFrame, payload Raw, err error) (frame []byte, outErr error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				frame = nil
				outErr = e
			} else {
				panic(p)
			}
		}
	}()
	reply := OAServiceReply{Version: 1, Service: v.Service, Method: v.Method, Ok: err == nil, Payload: payload}
	if err != nil {
		e := OAServiceError{Code: "handler_error", Message: "handler failed"}
		switch x := err.(type) {
		case *ServiceError:
			if x.Code != "" {
				e.Code = x.Code
			}
			e.Message = x.Message
		case DispatchError:
			e.Code = string(x)
			e.Message = ""
		case *Refusal:
			e.Code = x.Word
			e.Message = ""
		}
		reply.Payload = Raw(encOAServiceError(nil, &e, 1))
	}
	frame = encOAServiceReply(nil, &reply, 0)
	// Validate even error diagnostics before making them visible on the wire.
	r := &reader{buf: frame}
	r.ws()
	if _, e := r.decodeOAServiceReply(); e != nil {
		return nil, e
	}
	return frame, nil
}

type Resolver interface {
	Resolve(ResolveRequest) (ResolveResult, error)
}
type ResolverTransport interface {
	FrameExchanger
}
type ResolverClient struct{ transport ResolverTransport }

func NewResolverClient(t ResolverTransport) *ResolverClient { return &ResolverClient{transport: t} }

type ResolverDispatcher struct{ Handler Resolver }

func (c *ResolverClient) Resolve(arg0 ResolveRequest) (result ResolveResult, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OAResolverResolveArguments{Request: arg0}
	v := OAServiceFrame{Version: 1, Service: "abstraction.facade/resolver@1", Method: "Resolve", Arguments: Raw(encOAResolverResolveArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OAResolverResolveResult
	decoded, err = r.decodeOAResolverResolveResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (d *ResolverDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "abstraction.facade/resolver@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "Resolve":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *ResolverDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != "abstraction.facade/resolver@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "Resolve":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAResolverResolveArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeResolve(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *ResolverDispatcher) invokeResolve(args *OAResolverResolveArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result ResolveResult
	result, err = d.Handler.Resolve(args.Request)
	if err != nil {
		return
	}
	value := OAResolverResolveResult{Value: result}
	payload = Raw(encOAResolverResolveResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAResolverResolveResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
