// Code generated by abstraction-idl from abstraction-facade/facade.thrift. DO NOT EDIT.

package facade

import canonical "github.com/openabstractions/abstraction-facade/go-core/go/abstraction/facade"

// Exported data initially shares canonical values; variable reassignment is package-local.
type Raw = canonical.Raw

var ScopeNames = canonical.ScopeNames

const ScopeAny = canonical.ScopeAny
const ScopeLocal = canonical.ScopeLocal
const ScopeRemote = canonical.ScopeRemote
const ScopeUnknown = canonical.ScopeUnknown

var ResolutionStatusNames = canonical.ResolutionStatusNames

const ResolutionStatusResolved = canonical.ResolutionStatusResolved
const ResolutionStatusUnavailable = canonical.ResolutionStatusUnavailable
const ResolutionStatusForbidden = canonical.ResolutionStatusForbidden
const ResolutionStatusIncompatible = canonical.ResolutionStatusIncompatible
const ResolutionStatusUnmetRequirements = canonical.ResolutionStatusUnmetRequirements
const ResolutionStatusNotReady = canonical.ResolutionStatusNotReady
const ResolutionStatusInvalidRequest = canonical.ResolutionStatusInvalidRequest
const ResolutionStatusUnknown = canonical.ResolutionStatusUnknown

var BootstrapStateNames = canonical.BootstrapStateNames

const BootstrapStateUnknown = canonical.BootstrapStateUnknown
const BootstrapStateInstalled = canonical.BootstrapStateInstalled
const BootstrapStateStarting = canonical.BootstrapStateStarting
const BootstrapStateRunning = canonical.BootstrapStateRunning
const BootstrapStateUnavailable = canonical.BootstrapStateUnavailable
const BootstrapStateUnknownPolicy = canonical.BootstrapStateUnknownPolicy

var DefaultRuntimeContracts = canonical.DefaultRuntimeContracts

type ResolveRequest = canonical.ResolveRequest
type ServiceReference = canonical.ServiceReference
type ResolveResult = canonical.ResolveResult
type BootstrapObservation = canonical.BootstrapObservation
type CapabilityObservation = canonical.CapabilityObservation
type RuntimeObservation = canonical.RuntimeObservation
type OAResolverResolveArguments = canonical.OAResolverResolveArguments
type OAServiceFrame = canonical.OAServiceFrame
type OAServiceReply = canonical.OAServiceReply
type OAServiceError = canonical.OAServiceError
type OAResolverResolveResult = canonical.OAResolverResolveResult

func Encode(v *ResolveResult) []byte { return canonical.Encode(v) }

type Refusal = canonical.Refusal

func Decode(in []byte) (*ResolveResult, error) { return canonical.Decode(in) }

var Refusals = canonical.Refusals

func RefusalRank(word string) int { return canonical.RefusalRank(word) }

type FrameWriter = canonical.FrameWriter
type DispatchError = canonical.DispatchError
type FrameExchanger = canonical.FrameExchanger
type ServiceError = canonical.ServiceError
type Resolver = canonical.Resolver
type ResolverTransport = canonical.ResolverTransport
type ResolverClient = canonical.ResolverClient

func NewResolverClient(t ResolverTransport) *ResolverClient { return canonical.NewResolverClient(t) }

type ResolverDispatcher = canonical.ResolverDispatcher
