// Code generated by abstraction-idl from abstraction-facade/facade.thrift. DO NOT EDIT.

// abstraction.facade: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

export type Activation = (typeof Activation)[keyof typeof Activation];
export declare const Activation: Readonly<{ OnDemand: "on_demand"; Attach: "attach"; Remote: "remote" }>;

export type ApplicationActivationOutcome = (typeof ApplicationActivationOutcome)[keyof typeof ApplicationActivationOutcome];
export declare const ApplicationActivationOutcome: Readonly<{ Ready: "ready"; Unknown: "unknown"; Disabled: "disabled"; Forbidden: "forbidden"; Invalid: "invalid"; LaunchRefused: "launch_refused"; IdentityRefused: "identity_refused"; NotReady: "not_ready"; Unavailable: "unavailable" }>;

// Operator-trusted recipe for one bounded start of descriptor.program in the
// owning user's current runtime session. arguments contains at most 64 literal
// arguments of 1..4096 bytes. readiness identifies the interface a
// descriptor-program-and-session-bound announcement must supply.
// readiness_timeout_ms is one 100..30000 budget across executable inspection,
// launch and readiness. The recipe grants no document-open, focus,
// installation, termination or restart authority.
export interface ApplicationActivationRecipe {
  arguments: string[];
  readiness: ApplicationInterface;
  readinessTimeoutMs: bigint;
}

// ready identifies a descriptor-program-and-session-bound presence whose
// claimed interface matches the recipe; it is not a protocol probe or
// process-lineage proof. started says the platform launcher accepted the recipe
// during this shared attempt; the returned instance may be a fresh announcement
// from an already-running matching program. false means an existing matching
// instance was reused before launch. Cancellation returns unavailable to that
// waiter and leaves the bounded attempt and user application alive. Failure
// outcomes carry no instance.
export interface ApplicationActivationResult {
  outcome: ApplicationActivationOutcome;
  instance: string;
  started: boolean;
  reason: string;
}

// applied confirms the change; an announcement returns its opaque instance.
// stale means the instance expired or belongs to an earlier runtime epoch.
// Refusals carry no instance and never launch an app.
export interface ApplicationChange {
  outcome: ApplicationOutcome;
  instance: string;
  reason: string;
}

// A bounded application-owned context identifier, display title and revision
// claim. It is scoped to the service-assigned instance epoch; a reused context
// name after restart is a different object. A revision claim supplies no
// authorization or atomic mutation guarantee.
export interface ApplicationContext {
  name: string;
  title: string;
  revision: string;
}

// Operator-approved installed application. name is a stable 1..64-byte
// identifier; program is its normalized absolute native program identity. title
// and start_guidance are attributed display text, bounded to 256 and 4096
// bytes. Guidance is inert. activation is a separately typed operator-trusted
// recipe; absence disables activation. Registration grants no invocation or
// execution authority. This descriptor survives an application's exit.
export interface ApplicationDescriptor {
  name: string;
  program: string;
  title: string;
  startGuidance: string;
  activation: ApplicationActivationRecipe | null;
}

// One installed application's descriptor with its currently leased instances.
// scope records directory provenance; this local profile supplies local and
// never imports remote announcements. An empty instance list makes no claim
// about whether an unregistered process is running.
export interface ApplicationEntry {
  descriptor: ApplicationDescriptor;
  instances: ApplicationInstance[];
  scope: Scope;
}

// A current caller-visible instance and its attributed metadata. Handle
// ownership is enforced by OA. Possession of the handle grants no rights.
export interface ApplicationInstance {
  instance: string;
  interfaces: ApplicationInterface[];
  contexts: ApplicationContext[];
  expiresUnixMs: bigint;
}

// An application's claimed interface metadata. name identifies it within one
// instance; protocol and contract describe claimed support. No connection
// address or executable authority is conveyed. Invocation requires an
// independently authorized OA mediation binding.
export interface ApplicationInterface {
  name: string;
  protocol: string;
  contract: string;
}

export type ApplicationOutcome = (typeof ApplicationOutcome)[keyof typeof ApplicationOutcome];
export declare const ApplicationOutcome: Readonly<{ Applied: "applied"; Page: "page"; Unknown: "unknown"; Stale: "stale"; Conflict: "conflict"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// A complete bounded permission-filtered snapshot: at most 64 descriptors and
// 128 total live instances. Cursor is bound to caller, visible state and
// runtime epoch. Observe rechecks permissions before every answer. A cursor
// from another runtime epoch returns stale with a fresh full snapshot; no
// incremental continuity is claimed. Outcomes other than page or stale carry no
// cursor or entries.
export interface ApplicationPage {
  outcome: ApplicationOutcome;
  cursor: string;
  applications: ApplicationEntry[];
}

// Announce or renew the bound program's own instance in the runtime's verified
// local session. Empty instance requests a new opaque handle; a nonempty handle
// renews exactly its owner and session in the current runtime epoch. At most 16
// distinct interfaces and 32 distinct contexts, each identifier 1..64 bytes.
// The complete JSON-encoded presence is at most 2048 bytes. lease_ms is
// 1000..60000. Expiration establishes absence of fresh evidence, not a clean
// exit.
export interface ApplicationPresence {
  application: string;
  instance: string;
  interfaces: ApplicationInterface[];
  contexts: ApplicationContext[];
  leaseMs: bigint;
}

/** Experimental application-presence profile owned by the OA service. Persistent operator descriptors and transient app announcements have distinct authority and lifetime. This is a local directory; MCP/UI metadata are claims, and invocation remains behind OA capability mediation. Native callers retain their actual account/program identity. Unsupported platform identity refuses access. */
export declare class ApplicationsClient {
  constructor(transport: FrameTransport);
  /** Add an installed descriptor. Requires application.manage on account; existing names conflict. Does not launch or grant use. Programs cannot self-register. */
  register(descriptor: ApplicationDescriptor): Promise<ApplicationChange>;
  /** Remove an installed descriptor and its presence. Requires application.manage on account. Does not terminate user applications. */
  remove(application: string): Promise<ApplicationChange>;
  /** Publish or renew presence. Requires application.announce on app:<name>, a bound native program and kernel session matching this runtime, and current owner/session/epoch for renewal. Claims never alter descriptors or grants. */
  announce(presence: ApplicationPresence): Promise<ApplicationChange>;
  /** Withdraw only the bound program and session's own current instance. Requires application.announce on app:<name>. Does not terminate the application or remove its installed descriptor. */
  withdraw(application: string, instance: string): Promise<ApplicationChange>;
  /** Read or wait for a caller-filtered complete snapshot. Requires application.read on each returned app:<name>; hidden entries and changes remain undisclosed. Empty cursor answers immediately. wait_ms is 0..30000; permissions and lease expiry are rechecked while waiting. No activation occurs. */
  observe(cursor: string, waitMs: bigint): Promise<ApplicationPage>;
  /** Reuse a matching descriptor-program-bound presence or share one bounded authorized start attempt in this local runtime session. Requires application.activate on app:<name>. Only the operator-registered typed recipe executes; guidance and announcements remain inert. Caller cancellation stops its wait and never terminates or restarts the application. */
  activate(application: string): Promise<ApplicationActivationResult>;
}

export declare const ApplicationsService: Readonly<{ wireName: "abstraction.facade/applications@1"; Client: typeof ApplicationsClient }>;

// Read-only platform registration or supervisor evidence. Unknown means
// observation is unavailable; unavailable requires actual evidence that the
// selected registration is absent. Installed and starting require registration
// or supervisor evidence. Running describes a supervisor process and does not
// establish capability readiness. A missing endpoint alone establishes none of
// these states. Detail is diagnostic text, never authority or a recovery
// instruction.
export interface BootstrapObservation {
  state: BootstrapState;
  detail: string;
}

export type BootstrapState = (typeof BootstrapState)[keyof typeof BootstrapState];
export declare const BootstrapState: Readonly<{ Unknown: "unknown"; Installed: "installed"; Starting: "starting"; Running: "running"; Unavailable: "unavailable" }>;

// One native Peer attribute: user, process, path, package or code, in that
// order. proof is the abstraction.identity Proof name the receiving boundary
// established for this connection's caller. ceiling is the best Proof name the
// receiving platform's transport can reach for that attribute. Both are
// asserted by the receiving runtime and are display words, never authority.
export interface CallerAttribute {
  attribute: string;
  proof: string;
  ceiling: string;
}

/** The runtime resolver endpoint's echo of its bound caller, for diagnostics such as the control panel. Local transport only: a remote service states its own authentication and never inherits these proofs. */
export declare class CallerClient {
  constructor(transport: FrameTransport);
  /** Return what the receiving boundary bound for this connection's caller. It is the same Program evidence every runtime-hosted local service requires. unavailable means the binding could not be rechecked; forbidden is reserved for a boundary policy that withholds the echo; invalid for a request this provider cannot interpret. Observe grants, checks and changes nothing. */
  observe(): Promise<CallerObservation>;
}

// The receiving runtime's assertion of how it bound the caller. mechanism names
// the establishing facility as the logging service stamp does, identity/<os>.
// account is the Windows SID or the decimal POSIX uid, and program the
// executable path, each at the proof its attribute reports. pid is -1 where
// unestablished. platform, transport, bindable and stronger restate the
// receiving platform's identity ceiling: whether a binding pins the caller's
// process, and which transport would prove more (empty when none). Only
// observed carries identity; forbidden, unavailable and invalid carry empty
// strings, pid -1, no attributes, and bindable false.
export interface CallerObservation {
  outcome: CallerOutcome;
  mechanism: string;
  account: string;
  program: string;
  pid: bigint;
  attributes: CallerAttribute[];
  platform: string;
  transport: string;
  bindable: boolean;
  stronger: string;
}

export type CallerOutcome = (typeof CallerOutcome)[keyof typeof CallerOutcome];
export declare const CallerOutcome: Readonly<{ Observed: "observed"; Forbidden: "forbidden"; Unavailable: "unavailable"; Invalid: "invalid" }>;

export declare const CallerService: Readonly<{ wireName: "abstraction.facade/caller@1"; Client: typeof CallerClient }>;

// One authorized resolver observation. An absent result means unobserved
// because the query was not completed; it does not imply unavailable. Existing
// resolution statuses and disclosure rules apply unchanged. A resolved
// reference remains a candidate binding, not proof of successful provider
// calls.
export interface CapabilityObservation {
  request: ResolveRequest;
  result: ResolveResult | null;
}

// One provider outside the runtime. name is 1..64 bytes of a-z 0-9 _ - and
// unique. program is the absolute executable path the runtime launches and
// requires of the process serving endpoint; empty for a remote runtime.
// arguments are 0..64 strings of 1..4096 bytes; the argument {endpoint} is
// replaced by endpoint. endpoint is a local endpoint name of 1..64 bytes of a-z
// 0-9 _ . - for oa-native@1, and tls://<host>:<port> for oa-remote@1. transport
// is a DeclarationTransport member. contracts holds 1..16 distinct wire names
// of generated services the provider serves. guarantees holds 0..16 distinct
// names its candidates advertise. resources holds 0..64 distinct <kind>:<name>
// of declaration_resource_kinds, name 1..64 bytes of a-z 0-9 _ . -. models is
// the 0..64 distinct model names a native inference provider is trusted to
// serve, each 1..256 UTF-8 bytes without controls. on_demand launches program
// as a supervised child when a resolution first needs it; attach reads a
// provider something else started; remote is exactly the oa-remote@1
// activation, and remote is present exactly then.
export interface Declaration {
  name: string;
  program: string;
  arguments: string[];
  endpoint: string;
  transport: DeclarationTransport;
  contracts: string[];
  guarantees: string[];
  resources: string[];
  activation: Activation;
  remote: RemoteTrust | null;
  models: string[];
}

// applied carries the new revision; the runtime supervises, withdraws or stops
// the provider at once. reason is empty, or rules:<detail> when an acceptance
// rule could not be written. conflict means expected_revision is not current
// (reason revision), or Declare named an existing name or endpoint (reason name
// or endpoint), and carries the current revision. unknown means Withdraw named
// no declaration. invalid carries the field in reason, and program:self when
// the calling program declares itself. Other outcomes carry an empty revision.
export interface DeclarationChange {
  outcome: DeclarationEditOutcome;
  revision: string;
  reason: string;
}

export type DeclarationEditOutcome = (typeof DeclarationEditOutcome)[keyof typeof DeclarationEditOutcome];
export declare const DeclarationEditOutcome: Readonly<{ Applied: "applied"; Conflict: "conflict"; Unknown: "unknown"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// page carries every declaration in name order, at most 64, and the
// declarations' revision Declare and Withdraw take. invalid is reserved for a
// request the runtime cannot interpret. Refusals carry an empty revision and no
// declarations.
export interface DeclarationList {
  outcome: DeclarationListOutcome;
  revision: string;
  declarations: DeclarationState[];
}

export type DeclarationListOutcome = (typeof DeclarationListOutcome)[keyof typeof DeclarationListOutcome];
export declare const DeclarationListOutcome: Readonly<{ Page: "page"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// page carries every declaration and cursor, a digest of the declarations and
// their readings. It answers once cursor differs from the cursor given, or when
// wait_ms ends. invalid means wait_ms is outside 0..30000. Refusals carry an
// empty cursor and no declarations.
export interface DeclarationObservation {
  outcome: DeclarationListOutcome;
  cursor: string;
  declarations: DeclarationState[];
}

export type DeclarationReadiness = (typeof DeclarationReadiness)[keyof typeof DeclarationReadiness];
export declare const DeclarationReadiness: Readonly<{ Ready: "ready"; Idle: "idle"; Starting: "starting"; Restarting: "restarting"; Refused: "refused"; Unreachable: "unreachable"; NotReady: "not_ready" }>;

// A declaration and the runtime's latest reading of it. declared_by is the
// operator program that declared it. ready means endpoint@1 Describe, over a
// connection requiring program as the server, listed every declared contract
// ready. idle is an on_demand provider nothing has needed yet; starting a
// launched child not yet ready; restarting a child that exited and waits out
// its backoff; refused a process at endpoint running another program (why
// program:<detail>); unreachable a provider whose Describe failed (why
// describe:<code or detail>); not_ready a provider whose Describe lists a
// declared contract not ready or absent (why contract:<wire name>:<reason>).
// described is the last Description's services. accepted holds the resources a
// capability accepted at the last reading, such as store:<name> described by an
// inventory source and permitted by inventory.provide. restarts counts launches
// after the first.
export interface DeclarationState {
  declaration: Declaration;
  declaredBy: string;
  declaredUnixMs: bigint;
  readiness: DeclarationReadiness;
  why: string;
  restarts: bigint;
  described: ServiceState[];
  accepted: string[];
}

export type DeclarationTransport = (typeof DeclarationTransport)[keyof typeof DeclarationTransport];
export declare const DeclarationTransport: Readonly<{ Native: "oa-native@1"; Remote: "oa-remote@1" }>;

// described lists every service the endpoint hosts, in the endpoint's order.
// program and version are the display name and version the provider gives
// itself, possibly empty, and never authority: the caller binds the server by
// its own connection proof. forbidden is reserved for a boundary policy that
// withholds the description, unavailable for an endpoint that cannot describe
// itself now, and invalid for a request it cannot interpret. Refusals carry
// empty strings and no services.
export interface Description {
  outcome: DescriptionOutcome;
  program: string;
  version: string;
  services: ServiceState[];
}

export type DescriptionOutcome = (typeof DescriptionOutcome)[keyof typeof DescriptionOutcome];
export declare const DescriptionOutcome: Readonly<{ Described: "described"; Forbidden: "forbidden"; Unavailable: "unavailable"; Invalid: "invalid" }>;

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

/** The base-protocol description every generated endpoint serves beside its own contracts. A registry probes readiness with it over a connection that requires the declared program as the server. An endpoint built before this service answers unknown_service. */
export declare class EndpointClient {
  constructor(transport: FrameTransport);
  /** Describe the services this endpoint hosts and each one's readiness. Grants, checks and changes nothing. */
  describe(): Promise<Description>;
}

export declare const EndpointService: Readonly<{ wireName: "abstraction.facade/endpoint@1"; Client: typeof EndpointClient }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

/** The runtime's provider declarations, for operator tools. Applications never read it; they resolve. Each call is a rights decision for the bound operator subject; same-account identity alone grants nothing. A decision point that cannot answer reads unavailable. The registry is local: a remote runtime's services come from its own endpoint@1 Describe, and no registry is read across machines. */
export declare class RegistryClient {
  constructor(transport: FrameTransport);
  /** Read every declaration and its reading. Gated by abstraction.facade/provider.manage on resource account. */
  declarations(): Promise<DeclarationList>;
  /** Conditionally add one declaration, kept as providers/<name>.json in the runtime state. Gated by provider.manage. A program cannot declare itself (invalid, program:self). A store:<name> resource writes the permit rule abstraction.storage/inventory.provide on store:<name> for program, and a remote declaration writes abstraction.inference/complete on host:<name> for the runtime's operator programs and the caller; an existing rule on a target is left as it is. A declaration grants nothing else. */
  declare(expectedRevision: string, declaration: Declaration): Promise<DeclarationChange>;
  /** Conditionally remove one declaration: the runtime withdraws its candidates and hosts and ends a launched child. Gated by provider.manage. Rules are left as they are. */
  withdraw(expectedRevision: string, name: string): Promise<DeclarationChange>;
  /** Wait up to wait_ms milliseconds for the declarations or their readings to differ from cursor, then read them. An empty cursor answers at once. Gated by provider.manage. */
  observe(cursor: string, waitMs: bigint): Promise<DeclarationObservation>;
}

export declare const RegistryService: Readonly<{ wireName: "abstraction.facade/registry@1"; Client: typeof RegistryClient }>;

// The explicit mutual-TLS trust of a remote runtime. server_name is the name
// its certificate must carry. roots, certificate and key are absolute paths of
// PEM files on this machine: the roots trusted for that server, and this
// runtime's client certificate and private key, which the remote maps to its
// own caller. credential, when present, names the abstraction.credentials
// record the remote holds and applies to requests delegated to it. The paths
// are configuration; no key material travels in registry@1.
export interface RemoteTrust {
  serverName: string;
  roots: string;
  certificate: string;
  key: string;
  credential: string;
}

export type ResolutionStatus = (typeof ResolutionStatus)[keyof typeof ResolutionStatus];
export declare const ResolutionStatus: Readonly<{ Resolved: "resolved"; Unavailable: "unavailable"; Forbidden: "forbidden"; Incompatible: "incompatible"; UnmetRequirements: "unmet_requirements"; NotReady: "not_ready"; InvalidRequest: "invalid_request" }>;

// Capability and acceptable contract identities, required guarantees and
// permitted placement. Contains no caller identity or provider preference.
// Contract list must be nonempty; guarantees may be empty.
export interface ResolveRequest {
  capability: string;
  contracts: string[];
  guarantees: string[];
  scope: Scope;
}

// Reference is present exactly when resolved. Failure status describes the
// first unsatisfied resolution stage without exposing disallowed provider
// metadata. Service authentication and acceptance remain necessary after
// resolution.
export interface ResolveResult {
  status: ResolutionStatus;
  reference: ServiceReference | null;
}

/** Common provider resolution vocabulary. Authorization comes from the receiving boundary, never from request fields. See RESOLUTION.md for selection and refusal semantics. */
export declare class ResolverClient {
  constructor(transport: FrameTransport);
  /** Find an authorized ready candidate satisfying an exact acceptable contract and all required guarantees. Does not submit work, activate an embedded provider, or transfer ownership. */
  resolve(request: ResolveRequest): Promise<ResolveResult>;
}

export declare const ResolverService: Readonly<{ wireName: "abstraction.facade/resolver@1"; Client: typeof ResolverClient }>;

// Client-composed point-in-time diagnostics, with no new service or activation
// operation. Platform evidence is explicit and may be unknown. Capability
// queries use one caller waiting budget and authority; observations are
// sequential and not an atomic snapshot. Transport or cancellation errors are
// reported separately by the language observation API; unanswered entries
// retain absent results.
export interface RuntimeObservation {
  bootstrap: BootstrapObservation;
  capabilities: CapabilityObservation[];
}

export type Scope = (typeof Scope)[keyof typeof Scope];
export declare const Scope: Readonly<{ Any: "any"; Local: "local"; Remote: "remote" }>;

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode" }>;

export type ServiceReadiness = (typeof ServiceReadiness)[keyof typeof ServiceReadiness];
export declare const ServiceReadiness: Readonly<{ Ready: "ready"; NotReady: "not_ready"; Unknown: "unknown" }>;

// A candidate service binding, not acceptance or authority. Provider identifies
// a logical provider, not a PID. Scope is the concrete execution placement,
// local or remote; transport and endpoint describe the application connection.
// Both placements can bind a local OA endpoint whose service enforces that
// placement. Contract is an exact versioned service identity; endpoint is
// opaque to application code.
export interface ServiceReference {
  provider: string;
  capability: string;
  contract: string;
  guarantees: string[];
  scope: Scope;
  transport: string;
  endpoint: string;
}

// One service an endpoint hosts. contract is its wire name. readiness is ready
// unless the handler's readiness hook reports otherwise; why names the reason
// when it is not ready and is empty when ready. guarantees are those the
// provider states for the service. capabilities is an open map of display
// facts, such as profiles: chat,embed. None of it is authority.
export interface ServiceState {
  contract: string;
  readiness: ServiceReadiness;
  why: string;
  guarantees: string[];
  capabilities: { [key: string]: string };
}

export declare const declarationResourceKinds: readonly ["store", "host", "profile"];

export declare function decode(data: Uint8Array): ResolveResult;

export declare const defaultRuntimeContracts: readonly ["abstraction.logging/sink@1", "abstraction.config/reader@1", "abstraction.job/acceptance@1", "abstraction.job/operations@1", "abstraction.config/editor@1"];

export declare function encode(v: ResolveResult): Uint8Array;

export declare function newApplicationActivationRecipe(): ApplicationActivationRecipe;

export declare function newApplicationActivationResult(): ApplicationActivationResult;

export declare function newApplicationChange(): ApplicationChange;

export declare function newApplicationContext(): ApplicationContext;

export declare function newApplicationDescriptor(): ApplicationDescriptor;

export declare function newApplicationEntry(): ApplicationEntry;

export declare function newApplicationInstance(): ApplicationInstance;

export declare function newApplicationInterface(): ApplicationInterface;

export declare function newApplicationPage(): ApplicationPage;

export declare function newApplicationPresence(): ApplicationPresence;

export declare function newBootstrapObservation(): BootstrapObservation;

export declare function newCallerAttribute(): CallerAttribute;

export declare function newCallerObservation(): CallerObservation;

export declare function newCapabilityObservation(): CapabilityObservation;

export declare function newDeclaration(): Declaration;

export declare function newDeclarationChange(): DeclarationChange;

export declare function newDeclarationList(): DeclarationList;

export declare function newDeclarationObservation(): DeclarationObservation;

export declare function newDeclarationState(): DeclarationState;

export declare function newDescription(): Description;

export declare function newRemoteTrust(): RemoteTrust;

export declare function newResolveRequest(): ResolveRequest;

export declare function newResolveResult(): ResolveResult;

export declare function newRuntimeObservation(): RuntimeObservation;

export declare function newServiceReference(): ServiceReference;

export declare function newServiceState(): ServiceState;

export declare const registryActions: readonly ["abstraction.facade/provider.manage"];

export {};
