// Code generated by abstraction-idl from abstraction-facade/facade.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

export class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
export function num(out, n) { out.ascii(BigInt(n).toString()); }

export function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

export function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

export function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

export function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

export function encList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const ScopeNames = ["any", "local", "remote"];
export const ScopeUnknown = "refuse";

export const ResolutionStatusNames = ["resolved", "unavailable", "forbidden", "incompatible", "unmet_requirements", "not_ready", "invalid_request"];
export const ResolutionStatusUnknown = "refuse";

export const BootstrapStateNames = ["unknown", "installed", "starting", "running", "unavailable"];
export const BootstrapStateUnknown = "refuse";

export const defaultRuntimeContracts = ["abstraction.logging/sink@1", "abstraction.config/reader@1", "abstraction.job/acceptance@1", "abstraction.job/operations@1", "abstraction.config/editor@1"];

export function enc_resolverequest(out, v, depth) {
    if (typeof v.scope !== "string") throw new Refusal("wrong_type",0);
    if (v.scope !== "any" && v.scope !== "local" && v.scope !== "remote") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "capability");
  out.ascii(": ");
  esc(out, v.capability);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "contracts");
  out.ascii(": ");
  strs(out, v.contracts, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "guarantees");
  out.ascii(": ");
  strs(out, v.guarantees, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "scope");
  out.ascii(": ");
  esc(out, v.scope);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_servicereference(out, v, depth) {
    if (typeof v.scope !== "string") throw new Refusal("wrong_type",0);
    if (v.scope !== "any" && v.scope !== "local" && v.scope !== "remote") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "provider");
  out.ascii(": ");
  esc(out, v.provider);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "capability");
  out.ascii(": ");
  esc(out, v.capability);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "contract");
  out.ascii(": ");
  esc(out, v.contract);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "guarantees");
  out.ascii(": ");
  strs(out, v.guarantees, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "scope");
  out.ascii(": ");
  esc(out, v.scope);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "transport");
  out.ascii(": ");
  esc(out, v.transport);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "endpoint");
  out.ascii(": ");
  esc(out, v.endpoint);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_resolveresult(out, v, depth) {
    if (typeof v.status !== "string") throw new Refusal("wrong_type",0);
    if (v.status !== "resolved" && v.status !== "unavailable" && v.status !== "forbidden" && v.status !== "incompatible" && v.status !== "unmet_requirements" && v.status !== "not_ready" && v.status !== "invalid_request") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "status");
  out.ascii(": ");
  esc(out, v.status);
  if (v.reference !== undefined && v.reference !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "reference");
    out.ascii(": ");
    enc_servicereference(out, v.reference, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_bootstrapobservation(out, v, depth) {
    if (typeof v.state !== "string") throw new Refusal("wrong_type",0);
    if (v.state !== "unknown" && v.state !== "installed" && v.state !== "starting" && v.state !== "running" && v.state !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "state");
  out.ascii(": ");
  esc(out, v.state);
  if (v.detail !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "detail");
    out.ascii(": ");
    esc(out, v.detail);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_capabilityobservation(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request");
  out.ascii(": ");
  enc_resolverequest(out, v.request, depth + 1);
  if (v.result !== undefined && v.result !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "result");
    out.ascii(": ");
    enc_resolveresult(out, v.result, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_runtimeobservation(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "bootstrap");
  out.ascii(": ");
  enc_bootstrapobservation(out, v.bootstrap, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "capabilities");
  out.ascii(": ");
  encList(out, v.capabilities, depth + 1, enc_capabilityobservation);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaresolverresolvearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request");
  out.ascii(": ");
  enc_resolverequest(out, v.request, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceframe(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaservicereply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceerror(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaresolverresolveresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_resolveresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  enc_resolveresult(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function decodeList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

export function newResolveRequest() {
  return { capability: "", contracts: [], guarantees: [], scope: "" };
}

export function newServiceReference() {
  return { provider: "", capability: "", contract: "", guarantees: [], scope: "", transport: "", endpoint: "" };
}

export function newResolveResult() {
  return { status: "", reference: null };
}

export function newBootstrapObservation() {
  return { state: "", detail: "" };
}

export function newCapabilityObservation() {
  return { request: newResolveRequest(), result: null };
}

export function newRuntimeObservation() {
  return { bootstrap: newBootstrapObservation(), capabilities: [] };
}

export function newOAResolverResolveArguments() {
  return { request: newResolveRequest() };
}

export function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

export function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

export function newOAServiceError() {
  return { code: "", message: "" };
}

export function newOAResolverResolveResult() {
  return { value: newResolveResult() };
}

function decode_resolverequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResolveRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "capability") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.capability = r.string();
      } else if (key === "contracts") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.contracts = r.strList();
      } else if (key === "guarantees") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.guarantees = r.strList();
      } else if (key === "scope") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.scope = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.scope !== "any" && v.scope !== "local" && v.scope !== "remote") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_servicereference(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newServiceReference();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "provider") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.provider = r.string();
      } else if (key === "capability") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.capability = r.string();
      } else if (key === "contract") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.contract = r.string();
      } else if (key === "guarantees") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.guarantees = r.strList();
      } else if (key === "scope") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.scope = r.string();
      } else if (key === "transport") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.transport = r.string();
      } else if (key === "endpoint") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.endpoint = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 127) >>> 0) !== 127) throw r.refuse("missing_field");
    if (v.scope !== "any" && v.scope !== "local" && v.scope !== "remote") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_resolveresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResolveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "status") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.status = r.string();
      } else if (key === "reference") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.reference = decode_servicereference(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.status !== "resolved" && v.status !== "unavailable" && v.status !== "forbidden" && v.status !== "incompatible" && v.status !== "unmet_requirements" && v.status !== "not_ready" && v.status !== "invalid_request") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_bootstrapobservation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newBootstrapObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "state") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.state = r.string();
      } else if (key === "detail") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.detail = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.state !== "unknown" && v.state !== "installed" && v.state !== "starting" && v.state !== "running" && v.state !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_capabilityobservation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newCapabilityObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = decode_resolverequest(r);
      } else if (key === "result") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.result = decode_resolveresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_runtimeobservation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRuntimeObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "bootstrap") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.bootstrap = decode_bootstrapobservation(r);
      } else if (key === "capabilities") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.capabilities = decodeList(r, decode_capabilityobservation);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaresolverresolvearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAResolverResolveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = decode_resolverequest(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceframe(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaservicereply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceerror(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaresolverresolveresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAResolverResolveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_resolveresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = decode_resolveresult(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
export const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

export function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["ResolveRequest"] = [["capability","string","never"],["contracts","list<string>","never"],["guarantees","list<string>","never"],["scope","string","never"],];
_serviceRecords["ServiceReference"] = [["provider","string","never"],["capability","string","never"],["contract","string","never"],["guarantees","list<string>","never"],["scope","string","never"],["transport","string","never"],["endpoint","string","never"],];
_serviceRecords["ResolveResult"] = [["status","string","never"],["reference","ServiceReference","absent"],];
_serviceRecords["BootstrapObservation"] = [["state","string","never"],["detail","string","absent"],];
_serviceRecords["CapabilityObservation"] = [["request","ResolveRequest","never"],["result","ResolveResult","absent"],];
_serviceRecords["RuntimeObservation"] = [["bootstrap","BootstrapObservation","never"],["capabilities","list<CapabilityObservation>","never"],];
_serviceRecords["OAResolverResolveArguments"] = [["request","ResolveRequest","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAResolverResolveResult"] = [["value","ResolveResult","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(enc_oaserviceframe, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(decode_oaservicereply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(decode_oaserviceerror, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class ResolverClient {
  constructor(transport) { this._transport = transport; }
  async Resolve(arg0) {
    const args = newOAResolverResolveArguments();
    args["request"] = arg0;
    _serviceCheck("OAResolverResolveArguments", args);
    const payload = _serviceEncode(enc_oaresolverresolvearguments, args, 1);
    _serviceDecode(decode_oaresolverresolvearguments, payload, 1);
    const request = _serviceRequest("abstraction.facade/resolver@1", "Resolve", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.facade/resolver@1", "Resolve");
    const result = _serviceDecode(decode_oaresolverresolveresult, reply, 1);
    return result.value;
  }
}
export const ResolverService = Object.freeze({wireName:"abstraction.facade/resolver@1",Client:ResolverClient});
