// Code generated by abstraction-idl from abstraction-facade/facade.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::facade {

using Raw = std::string;

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

template <typename T>
inline void enc_list(std::string& out, const std::vector<T>& v, int depth,
                     void (*enc)(std::string&, const T&, int)) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        enc(out, v[i], depth + 1);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline const std::vector<std::string> kScopeNames = {"any", "local", "remote"};
inline const std::string kScopeUnknown = "refuse";

inline const std::vector<std::string> kResolutionStatusNames = {"resolved", "unavailable", "forbidden", "incompatible", "unmet_requirements", "not_ready", "invalid_request"};
inline const std::string kResolutionStatusUnknown = "refuse";

inline const std::vector<std::string> kBootstrapStateNames = {"unknown", "installed", "starting", "running", "unavailable"};
inline const std::string kBootstrapStateUnknown = "refuse";

inline const std::vector<std::string> kDefaultRuntimeContracts = {"abstraction.logging/sink@1", "abstraction.config/reader@1", "abstraction.job/acceptance@1", "abstraction.job/operations@1", "abstraction.config/editor@1"};

struct ResolveRequest {
    std::string capability;
    std::vector<std::string> contracts;
    std::vector<std::string> guarantees;
    std::string scope;
};

struct ServiceReference {
    std::string provider;
    std::string capability;
    std::string contract;
    std::vector<std::string> guarantees;
    std::string scope;
    std::string transport;
    std::string endpoint;
};

struct ResolveResult {
    std::string status;
    std::optional<ServiceReference> reference;
};

struct BootstrapObservation {
    std::string state;
    std::string detail;
};

struct CapabilityObservation {
    ResolveRequest request;
    std::optional<ResolveResult> result;
};

struct RuntimeObservation {
    BootstrapObservation bootstrap;
    std::vector<CapabilityObservation> capabilities;
};

struct OAResolverResolveArguments {
    ResolveRequest request;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

struct OAServiceReply {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    bool ok = false;
    Raw payload;
};

struct OAServiceError {
    std::string code;
    std::string message;
};

struct OAResolverResolveResult {
    ResolveResult value;
};

inline void enc_resolverequest(std::string& out, const ResolveRequest& v, int depth) {
    if (v.scope != "any" && v.scope != "local" && v.scope != "remote") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "capability");
    out += ": ";
    esc(out, v.capability);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "contracts");
    out += ": ";
    strs(out, v.contracts, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "guarantees");
    out += ": ";
    strs(out, v.guarantees, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "scope");
    out += ": ";
    esc(out, v.scope);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_servicereference(std::string& out, const ServiceReference& v, int depth) {
    if (v.scope != "any" && v.scope != "local" && v.scope != "remote") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "provider");
    out += ": ";
    esc(out, v.provider);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "capability");
    out += ": ";
    esc(out, v.capability);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "contract");
    out += ": ";
    esc(out, v.contract);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "guarantees");
    out += ": ";
    strs(out, v.guarantees, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "scope");
    out += ": ";
    esc(out, v.scope);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "transport");
    out += ": ";
    esc(out, v.transport);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "endpoint");
    out += ": ";
    esc(out, v.endpoint);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_resolveresult(std::string& out, const ResolveResult& v, int depth) {
    if (v.status != "resolved" && v.status != "unavailable" && v.status != "forbidden" && v.status != "incompatible" && v.status != "unmet_requirements" && v.status != "not_ready" && v.status != "invalid_request") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "status");
    out += ": ";
    esc(out, v.status);
    if (v.reference.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "reference");
        out += ": ";
        enc_servicereference(out, *v.reference, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_bootstrapobservation(std::string& out, const BootstrapObservation& v, int depth) {
    if (v.state != "unknown" && v.state != "installed" && v.state != "starting" && v.state != "running" && v.state != "unavailable") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "state");
    out += ": ";
    esc(out, v.state);
    if (!v.detail.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "detail");
        out += ": ";
        esc(out, v.detail);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_capabilityobservation(std::string& out, const CapabilityObservation& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "request");
    out += ": ";
    enc_resolverequest(out, v.request, depth + 1);
    if (v.result.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "result");
        out += ": ";
        enc_resolveresult(out, *v.result, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_runtimeobservation(std::string& out, const RuntimeObservation& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "bootstrap");
    out += ": ";
    enc_bootstrapobservation(out, v.bootstrap, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "capabilities");
    out += ": ";
    enc_list<CapabilityObservation>(out, v.capabilities, depth + 1, enc_capabilityobservation);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaresolverresolvearguments(std::string& out, const OAResolverResolveArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "request");
    out += ": ";
    enc_resolverequest(out, v.request, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceframe(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaservicereply(std::string& out, const OAServiceReply& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ok");
    out += ": ";
    out += v.ok ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "payload");
    out += ": ";
    out += v.payload;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceerror(std::string& out, const OAServiceError& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, v.code);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "message");
    out += ": ";
    esc(out, v.message);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaresolverresolveresult(std::string& out, const OAResolverResolveResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_resolveresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline std::string encode(const ResolveResult& v) {
    std::string out;
    enc_resolveresult(out, v, 0);
    out += '\n';
    return out;
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;



inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

template <typename T>
inline std::vector<T> decode_list(Reader& r, T (*elem)(Reader&)) {
    if (r.at() != '[') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::vector<T> out;
    r.skip_ws();
    if (r.at() != ']') {
        for (;;) {
            r.skip_ws();
            out.push_back(elem(r));
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != ']') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

inline ResolveRequest decode_resolverequest(Reader& r);
inline ServiceReference decode_servicereference(Reader& r);
inline ResolveResult decode_resolveresult(Reader& r);
inline BootstrapObservation decode_bootstrapobservation(Reader& r);
inline CapabilityObservation decode_capabilityobservation(Reader& r);
inline RuntimeObservation decode_runtimeobservation(Reader& r);
inline OAResolverResolveArguments decode_oaresolverresolvearguments(Reader& r);
inline OAServiceFrame decode_oaserviceframe(Reader& r);
inline OAServiceReply decode_oaservicereply(Reader& r);
inline OAServiceError decode_oaserviceerror(Reader& r);
inline OAResolverResolveResult decode_oaresolverresolveresult(Reader& r);

inline ResolveRequest decode_resolverequest(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ResolveRequest v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "capability") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.capability = r.str();
            } else if (key == "contracts") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.contracts = r.str_list();
            } else if (key == "guarantees") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.guarantees = r.str_list();
            } else if (key == "scope") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.scope = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    if (v.scope != "any" && v.scope != "local" && v.scope != "remote") { r.refuse("bad_enum"); }
    return v;
}

inline ServiceReference decode_servicereference(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ServiceReference v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "provider") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.provider = r.str();
            } else if (key == "capability") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.capability = r.str();
            } else if (key == "contract") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.contract = r.str();
            } else if (key == "guarantees") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.guarantees = r.str_list();
            } else if (key == "scope") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.scope = r.str();
            } else if (key == "transport") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.transport = r.str();
            } else if (key == "endpoint") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.endpoint = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 127u) != 127u) r.refuse("missing_field");
    if (v.scope != "any" && v.scope != "local" && v.scope != "remote") { r.refuse("bad_enum"); }
    return v;
}

inline ResolveResult decode_resolveresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ResolveResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "status") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.status = r.str();
            } else if (key == "reference") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.reference = decode_servicereference(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    if (v.status != "resolved" && v.status != "unavailable" && v.status != "forbidden" && v.status != "incompatible" && v.status != "unmet_requirements" && v.status != "not_ready" && v.status != "invalid_request") { r.refuse("bad_enum"); }
    return v;
}

inline BootstrapObservation decode_bootstrapobservation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    BootstrapObservation v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "state") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.state = r.str();
            } else if (key == "detail") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.detail = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    if (v.state != "unknown" && v.state != "installed" && v.state != "starting" && v.state != "running" && v.state != "unavailable") { r.refuse("bad_enum"); }
    return v;
}

inline CapabilityObservation decode_capabilityobservation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    CapabilityObservation v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "request") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.request = decode_resolverequest(r);
            } else if (key == "result") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.result = decode_resolveresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline RuntimeObservation decode_runtimeobservation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    RuntimeObservation v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "bootstrap") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.bootstrap = decode_bootstrapobservation(r);
            } else if (key == "capabilities") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.capabilities = decode_list<CapabilityObservation>(r, decode_capabilityobservation);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OAResolverResolveArguments decode_oaresolverresolvearguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAResolverResolveArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "request") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.request = decode_resolverequest(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oaserviceframe(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline OAServiceReply decode_oaservicereply(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceReply v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "ok") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.ok = r.boolean();
            } else if (key == "payload") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.payload = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline OAServiceError decode_oaserviceerror(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceError v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "code") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.code = r.str();
            } else if (key == "message") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.message = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OAResolverResolveResult decode_oaresolverresolveresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAResolverResolveResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_resolveresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline ResolveResult decode(std::string_view data) {
    Reader r{data};
    r.skip_ws();
    ResolveResult v = decode_resolveresult(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}

struct FrameWriter{virtual ~FrameWriter()=default;virtual void WriteFrame(std::string_view)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oaserviceframe(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}

struct FrameExchanger{virtual ~FrameExchanger()=default;virtual std::string ExchangeFrame(std::string_view)=0;};
struct ServiceError:std::runtime_error{std::string code,message;ServiceError(std::string c,std::string m):std::runtime_error(m.empty()?c:m),code(c),message(m){}};
inline Raw service_response(std::string_view frame,std::string_view service,std::string_view method){
 Reader r{frame};r.skip_ws();auto v=decode_oaservicereply(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");if(v.service!=service||v.method!=method)throw DispatchError("mismatched_response");
 if(!v.ok){Reader e{v.payload};e.depth=1;e.skip_ws();auto error=decode_oaserviceerror(e);e.skip_ws();if(e.pos!=e.buf.size())e.refuse("trailing_bytes");if(error.code.empty())throw DispatchError("invalid_error");throw ServiceError(error.code,error.message);}return v.payload;
}
inline std::string service_reply(const OAServiceFrame& request,const Raw& payload,const ServiceError* error=nullptr){
 OAServiceReply reply;reply.version=1;reply.service=request.service;reply.method=request.method;reply.ok=error==nullptr;reply.payload=payload;
 if(error){OAServiceError e;e.code=error->code.empty()?"handler_error":error->code;e.message=error->message;reply.payload.clear();enc_oaserviceerror(reply.payload,e,1);}
 std::string frame;enc_oaservicereply(frame,reply,0);Reader r{frame};r.skip_ws();decode_oaservicereply(r);return frame;
}
struct Resolver{virtual ~Resolver()=default;
virtual ResolveResult Resolve(const ResolveRequest& arg0)=0;
};
template<class Transport>struct ResolverClient:Resolver{Transport& transport_;explicit ResolverClient(Transport&t):transport_(t){}
ResolveResult Resolve(const ResolveRequest& arg0)override{OAResolverResolveArguments args;
args.request=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.facade/resolver@1";v.method="Resolve";enc_oaresolverresolvearguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oaresolverresolveresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct ResolverService{inline static constexpr std::string_view wire_name="abstraction.facade/resolver@1";inline static constexpr std::string_view capability="abstraction.facade";template<class Transport>using Client=ResolverClient<Transport>;};
struct ResolverDispatcher:FrameWriter,FrameExchanger{Resolver&handler;explicit ResolverDispatcher(Resolver&h):handler(h){}
void WriteFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.facade/resolver@1")throw DispatchError("unknown_service");
if(v.method=="Resolve"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string ExchangeFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.facade/resolver@1"){ServiceError e("unknown_service","");return service_reply(v,"",&e);}
try{
if(v.method=="Resolve"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oaresolverresolvearguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Resolve(args);return service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return service_reply(v,"",&error);}
}
Raw invoke_Resolve(const OAResolverResolveArguments&args){
ResolveResult result{};
try{
result=handler.Resolve(args.request);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OAResolverResolveResult value;
value.value=result;
Raw payload;enc_oaresolverresolveresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oaresolverresolveresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
};

}  // namespace abstraction::facade
